apiVersion: v1
kind: Service
metadata:
  name: translation-service
spec:
  selector:
    app: translation-service
  ports:
    - protocol: TCP
      port: 9527
      targetPort: 9527
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-service
  template:
    metadata:
      labels:
        app: translation-service
    spec:
      containers:
        - name: translation-service
          image: jinxingzhang/translation_service_v1:0.0.0.1
          ports:
            - containerPort: 9527
          resources:
            limits:
              memory: "1024Mi"
              cpu: "512m"
